package com.sbnz.model;
// Generated Jul 21, 2018 12:49:21 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Disease generated by hbm2java
 */
@Entity
@Table(name = "disease", catalog = "sbnz")
public class Disease implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long diseaseId;
	private Diagnosis diagnosis;
	private Medicine medicine;
	private String diseaseName;
	private Set<Symptom> symptoms = new HashSet<Symptom>(0);

	public Disease() {
	}

	public Disease(long diseaseId, String diseaseName) {
		this.diseaseId = diseaseId;
		this.diseaseName = diseaseName;
	}

	public Disease(long diseaseId, Diagnosis diagnosis, Medicine medicine, String diseaseName, Set<Symptom> symptoms) {
		this.diseaseId = diseaseId;
		this.diagnosis = diagnosis;
		this.medicine = medicine;
		this.diseaseName = diseaseName;
		this.symptoms = symptoms;
	}

	@Id
	@GenericGenerator(name = "generator", strategy = "increment")
	@GeneratedValue(generator="generator")
	@Column(name = "DISEASE_ID", unique = true, nullable = false)
	public long getDiseaseId() {
		return this.diseaseId;
	}

	public void setDiseaseId(long diseaseId) {
		this.diseaseId = diseaseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIAGNOSIS_ID")
	public Diagnosis getDiagnosis() {
		return this.diagnosis;
	}

	public void setDiagnosis(Diagnosis diagnosis) {
		this.diagnosis = diagnosis;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEDICINE_ID")
	public Medicine getMedicine() {
		return this.medicine;
	}

	public void setMedicine(Medicine medicine) {
		this.medicine = medicine;
	}

	@Column(name = "DISEASE_NAME", nullable = false, length = 100)
	public String getDiseaseName() {
		return this.diseaseName;
	}

	public void setDiseaseName(String diseaseName) {
		this.diseaseName = diseaseName;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "diseases")
	public Set<Symptom> getSymptoms() {
		return this.symptoms;
	}

	public void setSymptoms(Set<Symptom> symptoms) {
		this.symptoms = symptoms;
	}

}
