package com.sbnz.model;
// Generated Jul 21, 2018 12:49:21 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Ingredient generated by hbm2java
 */
@Entity
@Table(name = "ingredient", catalog = "sbnz")
public class Ingredient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long ingredientId;
	private String ingredientName;
	private Set<Medicine> medicines = new HashSet<Medicine>(0);
	private Set<Patient> patients = new HashSet<Patient>(0);

	public Ingredient() {
	}

	public Ingredient(long ingredientId, String ingredientName) {
		this.ingredientId = ingredientId;
		this.ingredientName = ingredientName;
	}

	public Ingredient(long ingredientId, String ingredientName, Set<Medicine> medicines, Set<Patient> patients) {
		this.ingredientId = ingredientId;
		this.ingredientName = ingredientName;
		this.medicines = medicines;
		this.patients = patients;
	}

	@Id
	@GenericGenerator(name = "generator", strategy = "increment")
	@Column(name = "INGREDIENT_ID", unique = true, nullable = false)
	public long getIngredientId() {
		return this.ingredientId;
	}

	public void setIngredientId(long ingredientId) {
		this.ingredientId = ingredientId;
	}

	@Column(name = "INGREDIENT_NAME", nullable = false, length = 250)
	public String getIngredientName() {
		return this.ingredientName;
	}

	public void setIngredientName(String ingredientName) {
		this.ingredientName = ingredientName;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "ingredients")
	public Set<Medicine> getMedicines() {
		return this.medicines;
	}

	public void setMedicines(Set<Medicine> medicines) {
		this.medicines = medicines;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "ingredients")
	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

}
