package com.sbnz.model;
// Generated Jul 21, 2018 12:49:21 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name = "patient", catalog = "sbnz")
public class Patient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long patientId;
	private User user;
	private String patientName;
	private String patientSurname;
	private int patientBloodPressure;
	private Float patientTemperature;
	private Set<Ingredient> ingredients = new HashSet<Ingredient>(0);

	public Patient() {
	}

	public Patient(long patientId, User user, String patientName, String patientSurname, int patientBloodPressure) {
		this.patientId = patientId;
		this.user = user;
		this.patientName = patientName;
		this.patientSurname = patientSurname;
		this.patientBloodPressure = patientBloodPressure;
	}

	public Patient(long patientId, User user, String patientName, String patientSurname, int patientBloodPressure,
			Float patientTemperature, Set<Ingredient> ingredients) {
		this.patientId = patientId;
		this.user = user;
		this.patientName = patientName;
		this.patientSurname = patientSurname;
		this.patientBloodPressure = patientBloodPressure;
		this.patientTemperature = patientTemperature;
		this.ingredients = ingredients;
	}

	@Id
	@GenericGenerator(name = "generator", strategy = "increment")
	@GeneratedValue(generator="generator")
	@Column(name = "PATIENT_ID", unique = true, nullable = false)
	public long getPatientId() {
		return this.patientId;
	}

	public void setPatientId(long patientId) {
		this.patientId = patientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "PATIENT_NAME", nullable = false, length = 100)
	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	@Column(name = "PATIENT_SURNAME", nullable = false, length = 250)
	public String getPatientSurname() {
		return this.patientSurname;
	}

	public void setPatientSurname(String patientSurname) {
		this.patientSurname = patientSurname;
	}

	@Column(name = "PATIENT_BLOOD_PRESSURE", nullable = false)
	public int getPatientBloodPressure() {
		return this.patientBloodPressure;
	}

	public void setPatientBloodPressure(int patientBloodPressure) {
		this.patientBloodPressure = patientBloodPressure;
	}

	@Column(name = "PATIENT_TEMPERATURE", precision = 12, scale = 0)
	public Float getPatientTemperature() {
		return this.patientTemperature;
	}

	public void setPatientTemperature(Float patientTemperature) {
		this.patientTemperature = patientTemperature;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "allergic_to", catalog = "sbnz", joinColumns = {
			@JoinColumn(name = "PATIENT_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "INGREDIENT_ID", nullable = false, updatable = false) })
	public Set<Ingredient> getIngredients() {
		return this.ingredients;
	}

	public void setIngredients(Set<Ingredient> ingredients) {
		this.ingredients = ingredients;
	}

}
