package com.sbnz.model;
// Generated Jul 21, 2018 12:49:21 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Symptom generated by hbm2java
 */
@Entity
@Table(name = "symptom", catalog = "sbnz")
public class Symptom implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long symId;
	private String symDesc;
	private Set<Disease> diseases = new HashSet<Disease>(0);

	public Symptom() {
	}

	public Symptom(long symId, String symDesc) {
		this.symId = symId;
		this.symDesc = symDesc;
	}

	public Symptom(long symId, String symDesc, Set<Disease> diseases) {
		this.symId = symId;
		this.symDesc = symDesc;
		this.diseases = diseases;
	}

	@Id
	@GenericGenerator(name = "generator", strategy = "increment")
	@GeneratedValue(generator="generator")
	@Column(name = "SYM_ID", unique = true, nullable = false)
	public long getSymId() {
		return this.symId;
	}

	public void setSymId(long symId) {
		this.symId = symId;
	}

	@Column(name = "SYM_DESC", nullable = false, length = 250)
	public String getSymDesc() {
		return this.symDesc;
	}

	public void setSymDesc(String symDesc) {
		this.symDesc = symDesc;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "has", catalog = "sbnz", joinColumns = {
			@JoinColumn(name = "SYM_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "DISEASE_ID", nullable = false, updatable = false) })
	public Set<Disease> getDiseases() {
		return this.diseases;
	}

	public void setDiseases(Set<Disease> diseases) {
		this.diseases = diseases;
	}

}
