package com.sbnz.doctor.model;
// Generated Jul 24, 2018 3:48:04 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Diagnosis generated by hbm2java
 */
@Entity
@Table(name = "diagnosis", catalog = "sbnz")
public class Diagnosis implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long diagnosisId;
	private Date diagnosisDate;
	private Set<Disease> diseases = new HashSet<Disease>(0);

	public Diagnosis() {
	}

	public Diagnosis(Date diagnosisDate) {
		this.diagnosisDate = diagnosisDate;
	}

	public Diagnosis(Date diagnosisDate, Set<Disease> diseases) {
		this.diagnosisDate = diagnosisDate;
		this.diseases = diseases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DIAGNOSIS_ID", unique = true, nullable = false)
	public Long getDiagnosisId() {
		return this.diagnosisId;
	}

	public void setDiagnosisId(Long diagnosisId) {
		this.diagnosisId = diagnosisId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DIAGNOSIS_DATE", nullable = false, length = 10)
	public Date getDiagnosisDate() {
		return this.diagnosisDate;
	}

	public void setDiagnosisDate(Date diagnosisDate) {
		this.diagnosisDate = diagnosisDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosis")
	public Set<Disease> getDiseases() {
		return this.diseases;
	}

	public void setDiseases(Set<Disease> diseases) {
		this.diseases = diseases;
	}

}
