package com.sbnz.doctor.model;
// Generated Jul 24, 2018 3:48:04 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Disease generated by hbm2java
 */
@Entity
@Table(name = "disease", catalog = "sbnz")
public class Disease implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long diseaseId;
	private Diagnosis diagnosis;
	private Medicine medicine;
	private String diseaseName;
	private Set<Symptom> symptoms = new HashSet<Symptom>(0);

	public Disease() {
	}

	public Disease(String diseaseName) {
		this.diseaseName = diseaseName;
	}

	public Disease(Diagnosis diagnosis, Medicine medicine, String diseaseName, Set<Symptom> symptoms) {
		this.diagnosis = diagnosis;
		this.medicine = medicine;
		this.diseaseName = diseaseName;
		this.symptoms = symptoms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DISEASE_ID", unique = true, nullable = false)
	public Long getDiseaseId() {
		return this.diseaseId;
	}

	public void setDiseaseId(Long diseaseId) {
		this.diseaseId = diseaseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIAGNOSIS_ID")
	public Diagnosis getDiagnosis() {
		return this.diagnosis;
	}

	public void setDiagnosis(Diagnosis diagnosis) {
		this.diagnosis = diagnosis;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEDICINE_ID")
	public Medicine getMedicine() {
		return this.medicine;
	}

	public void setMedicine(Medicine medicine) {
		this.medicine = medicine;
	}

	@Column(name = "DISEASE_NAME", nullable = false, length = 100)
	public String getDiseaseName() {
		return this.diseaseName;
	}

	public void setDiseaseName(String diseaseName) {
		this.diseaseName = diseaseName;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "diseases")
	public Set<Symptom> getSymptoms() {
		return this.symptoms;
	}

	public void setSymptoms(Set<Symptom> symptoms) {
		this.symptoms = symptoms;
	}

}
