package com.sbnz.doctor.model;
// Generated Jul 24, 2018 3:48:04 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Ingredient generated by hbm2java
 */
@Entity
@Table(name = "ingredient", catalog = "sbnz")
public class Ingredient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long ingredientId;
	private String ingredientName;
	private Set<Medicine> medicines = new HashSet<Medicine>(0);
	private Set<Patient> patients = new HashSet<Patient>(0);

	public Ingredient() {
	}

	public Ingredient(String ingredientName) {
		this.ingredientName = ingredientName;
	}

	public Ingredient(String ingredientName, Set<Medicine> medicines, Set<Patient> patients) {
		this.ingredientName = ingredientName;
		this.medicines = medicines;
		this.patients = patients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "INGREDIENT_ID", unique = true, nullable = false)
	public Long getIngredientId() {
		return this.ingredientId;
	}

	public void setIngredientId(Long ingredientId) {
		this.ingredientId = ingredientId;
	}

	@Column(name = "INGREDIENT_NAME", nullable = false, length = 250)
	public String getIngredientName() {
		return this.ingredientName;
	}

	public void setIngredientName(String ingredientName) {
		this.ingredientName = ingredientName;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "ingredients")
	public Set<Medicine> getMedicines() {
		return this.medicines;
	}

	public void setMedicines(Set<Medicine> medicines) {
		this.medicines = medicines;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "ingredients")
	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

}
