package com.sbnz.doctor.model;
// Generated Aug 26, 2018 4:00:55 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Medicineallergy generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "medicineallergy", catalog = "sbnz")
public class Medicineallergy implements java.io.Serializable {

	private Long medId;
	private Medicine medicine;
	private Patient patient;

	public Medicineallergy() {
	}

	public Medicineallergy(Medicine medicine, Patient patient) {
		this.medicine = medicine;
		this.patient = patient;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MED_ID", unique = true, nullable = false)
	public Long getMedId() {
		return this.medId;
	}

	public void setMedId(Long medId) {
		this.medId = medId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEDICINE_ID", nullable = false)
	public Medicine getMedicine() {
		return this.medicine;
	}

	public void setMedicine(Medicine medicine) {
		this.medicine = medicine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PATIENT_ID", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

}
