package com.sbnz.doctor.model;
// Generated Jul 24, 2018 3:48:04 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Medicine generated by hbm2java
 */
@Entity
@Table(name = "medicine", catalog = "sbnz")
public class Medicine implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long medicineId;
	private String medicineName;
	private char medicineType;
	private Set<Ingredient> ingredients = new HashSet<Ingredient>(0);
	private Set<Disease> diseases = new HashSet<Disease>(0);

	public Medicine() {
	}

	public Medicine(String medicineName, char medicineType) {
		this.medicineName = medicineName;
		this.medicineType = medicineType;
	}

	public Medicine(String medicineName, char medicineType, Set<Ingredient> ingredients, Set<Disease> diseases) {
		this.medicineName = medicineName;
		this.medicineType = medicineType;
		this.ingredients = ingredients;
		this.diseases = diseases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MEDICINE_ID", unique = true, nullable = false)
	public Long getMedicineId() {
		return this.medicineId;
	}

	public void setMedicineId(Long medicineId) {
		this.medicineId = medicineId;
	}

	@Column(name = "MEDICINE_NAME", nullable = false, length = 150)
	public String getMedicineName() {
		return this.medicineName;
	}

	public void setMedicineName(String medicineName) {
		this.medicineName = medicineName;
	}

	@Column(name = "MEDICINE_TYPE", nullable = false, length = 1)
	public char getMedicineType() {
		return this.medicineType;
	}

	public void setMedicineType(char medicineType) {
		this.medicineType = medicineType;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "contains", catalog = "sbnz", joinColumns = {
			@JoinColumn(name = "MEDICINE_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "INGREDIENT_ID", nullable = false, updatable = false) })
	public Set<Ingredient> getIngredients() {
		return this.ingredients;
	}

	public void setIngredients(Set<Ingredient> ingredients) {
		this.ingredients = ingredients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medicine")
	public Set<Disease> getDiseases() {
		return this.diseases;
	}

	public void setDiseases(Set<Disease> diseases) {
		this.diseases = diseases;
	}

}
