package com.sbnz.doctor.model;
// Generated Aug 26, 2018 4:00:55 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Patient generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "patient", catalog = "sbnz")
public class Patient implements java.io.Serializable {

	private Long patientId;
	private String patientName;
	private String patientSurname;
	private Set<Diagnosis> diagnosises = new HashSet<Diagnosis>(0);
	private Set<Allergy> allergies = new HashSet<Allergy>(0);
	private Set<Therapy> therapies = new HashSet<Therapy>(0);
	private Set<Medicineallergy> medicineallergies = new HashSet<Medicineallergy>(0);

	public Patient() {
	}

	public Patient(String patientName, String patientSurname) {
		this.patientName = patientName;
		this.patientSurname = patientSurname;
	}

	public Patient(String patientName, String patientSurname, Set<Diagnosis> diagnosises, Set<Allergy> allergies,
			Set<Therapy> therapies, Set<Medicineallergy> medicineallergies) {
		this.patientName = patientName;
		this.patientSurname = patientSurname;
		this.diagnosises = diagnosises;
		this.allergies = allergies;
		this.therapies = therapies;
		this.medicineallergies = medicineallergies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PATIENT_ID", unique = true, nullable = false)
	public Long getPatientId() {
		return this.patientId;
	}

	public void setPatientId(Long patientId) {
		this.patientId = patientId;
	}

	@Column(name = "PATIENT_NAME", nullable = false, length = 100)
	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	@Column(name = "PATIENT_SURNAME", nullable = false, length = 250)
	public String getPatientSurname() {
		return this.patientSurname;
	}

	public void setPatientSurname(String patientSurname) {
		this.patientSurname = patientSurname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Diagnosis> getDiagnosises() {
		return this.diagnosises;
	}

	public void setDiagnosises(Set<Diagnosis> diagnosises) {
		this.diagnosises = diagnosises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Allergy> getAllergies() {
		return this.allergies;
	}

	public void setAllergies(Set<Allergy> allergies) {
		this.allergies = allergies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Therapy> getTherapies() {
		return this.therapies;
	}

	public void setTherapies(Set<Therapy> therapies) {
		this.therapies = therapies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Medicineallergy> getMedicineallergies() {
		return this.medicineallergies;
	}

	public void setMedicineallergies(Set<Medicineallergy> medicineallergies) {
		this.medicineallergies = medicineallergies;
	}

}
