package com.sbnz.doctor.model;
// Generated Aug 11, 2018 4:31:23 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name = "patient", catalog = "sbnz")
public class Patient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2085871803800607606L;
	private Long patientId;
	private String patientName;
	private String patientSurname;
	private int patientBloodPressure;
	private Float patientTemperature;
	private Set<Diagnosis> diagnosises = new HashSet<Diagnosis>(0);
	private Set<Allergy> allergies = new HashSet<Allergy>(0);
	private Set<Therapy> therapies = new HashSet<Therapy>(0);

	public Patient() {
	}

	public Patient(String patientName, String patientSurname, int patientBloodPressure) {
		this.patientName = patientName;
		this.patientSurname = patientSurname;
		this.patientBloodPressure = patientBloodPressure;
	}

	public Patient(String patientName, String patientSurname, int patientBloodPressure, Float patientTemperature,
			Set<Diagnosis> diagnosises, Set<Allergy> allergies, Set<Therapy> therapies) {
		this.patientName = patientName;
		this.patientSurname = patientSurname;
		this.patientBloodPressure = patientBloodPressure;
		this.patientTemperature = patientTemperature;
		this.diagnosises = diagnosises;
		this.allergies = allergies;
		this.therapies = therapies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PATIENT_ID", unique = true, nullable = false)
	public Long getPatientId() {
		return this.patientId;
	}

	public void setPatientId(Long patientId) {
		this.patientId = patientId;
	}

	@Column(name = "PATIENT_NAME", nullable = false, length = 100)
	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	@Column(name = "PATIENT_SURNAME", nullable = false, length = 250)
	public String getPatientSurname() {
		return this.patientSurname;
	}

	public void setPatientSurname(String patientSurname) {
		this.patientSurname = patientSurname;
	}

	@Column(name = "PATIENT_BLOOD_PRESSURE", nullable = false)
	public int getPatientBloodPressure() {
		return this.patientBloodPressure;
	}

	public void setPatientBloodPressure(int patientBloodPressure) {
		this.patientBloodPressure = patientBloodPressure;
	}

	@Column(name = "PATIENT_TEMPERATURE", precision = 12, scale = 0)
	public Float getPatientTemperature() {
		return this.patientTemperature;
	}

	public void setPatientTemperature(Float patientTemperature) {
		this.patientTemperature = patientTemperature;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Diagnosis> getDiagnosises() {
		return this.diagnosises;
	}

	public void setDiagnosises(Set<Diagnosis> diagnosises) {
		this.diagnosises = diagnosises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Allergy> getAllergies() {
		return this.allergies;
	}

	public void setAllergies(Set<Allergy> allergies) {
		this.allergies = allergies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Therapy> getTherapies() {
		return this.therapies;
	}

	public void setTherapies(Set<Therapy> therapies) {
		this.therapies = therapies;
	}

}
