package com.sbnz.doctor.model;
// Generated Jul 24, 2018 3:48:04 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Symptom generated by hbm2java
 */
@Entity
@Table(name = "symptom", catalog = "sbnz")
public class Symptom implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long symId;
	private String symDesc;
	private Set<Disease> diseases = new HashSet<Disease>(0);

	public Symptom() {
	}

	public Symptom(String symDesc) {
		this.symDesc = symDesc;
	}

	public Symptom(String symDesc, Set<Disease> diseases) {
		this.symDesc = symDesc;
		this.diseases = diseases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SYM_ID", unique = true, nullable = false)
	public Long getSymId() {
		return this.symId;
	}

	public void setSymId(Long symId) {
		this.symId = symId;
	}

	@Column(name = "SYM_DESC", nullable = false, length = 300)
	public String getSymDesc() {
		return this.symDesc;
	}

	public void setSymDesc(String symDesc) {
		this.symDesc = symDesc;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "has", catalog = "sbnz", joinColumns = {
			@JoinColumn(name = "SYM_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "DISEASE_ID", nullable = false, updatable = false) })
	public Set<Disease> getDiseases() {
		return this.diseases;
	}

	public void setDiseases(Set<Disease> diseases) {
		this.diseases = diseases;
	}

}
