package com.sbnz.doctor.model;
// Generated Aug 26, 2018 4:00:55 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Symptom generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "symptom", catalog = "sbnz")
public class Symptom implements java.io.Serializable {

	private Long symId;
	private String symDesc;
	private String symCode;
	private boolean symSystem;
	private Set<Symptomdisease> symptomdiseases = new HashSet<Symptomdisease>(0);

	public Symptom() {
	}

	public Symptom(String symDesc, String symCode, boolean symSystem) {
		this.symDesc = symDesc;
		this.symCode = symCode;
		this.symSystem = symSystem;
	}

	public Symptom(String symDesc, String symCode, boolean symSystem, Set<Symptomdisease> symptomdiseases) {
		this.symDesc = symDesc;
		this.symCode = symCode;
		this.symSystem = symSystem;
		this.symptomdiseases = symptomdiseases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SYM_ID", unique = true, nullable = false)
	public Long getSymId() {
		return this.symId;
	}

	public void setSymId(Long symId) {
		this.symId = symId;
	}

	@Column(name = "SYM_DESC", nullable = false, length = 300)
	public String getSymDesc() {
		return this.symDesc;
	}

	public void setSymDesc(String symDesc) {
		this.symDesc = symDesc;
	}

	@Column(name = "SYM_CODE", nullable = false, length = 5, columnDefinition = "char")
	public String getSymCode() {
		return this.symCode;
	}

	public void setSymCode(String symCode) {
		this.symCode = symCode;
	}

	@Column(name = "SYM_SYSTEM", nullable = false)
	public boolean isSymSystem() {
		return this.symSystem;
	}

	public void setSymSystem(boolean symSystem) {
		this.symSystem = symSystem;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "symptom")
	public Set<Symptomdisease> getSymptomdiseases() {
		return this.symptomdiseases;
	}

	public void setSymptomdiseases(Set<Symptomdisease> symptomdiseases) {
		this.symptomdiseases = symptomdiseases;
	}

}
