package com.sbnz.doctor.model;
// Generated Aug 2, 2018 12:56:36 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Symptom generated by hbm2java
 */
@Entity
@Table(name = "symptom", catalog = "sbnz")
public class Symptom implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long symId;
	private String symDesc;
	private Set<Symptomdisease> symptomdiseases = new HashSet<Symptomdisease>(0);

	public Symptom() {
	}

	public Symptom(String symDesc) {
		this.symDesc = symDesc;
	}

	public Symptom(String symDesc, Set<Symptomdisease> symptomdiseases) {
		this.symDesc = symDesc;
		this.symptomdiseases = symptomdiseases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SYM_ID", unique = true, nullable = false)
	public Long getSymId() {
		return this.symId;
	}

	public void setSymId(Long symId) {
		this.symId = symId;
	}

	@Column(name = "SYM_DESC", nullable = false, length = 300)
	public String getSymDesc() {
		return this.symDesc;
	}

	public void setSymDesc(String symDesc) {
		this.symDesc = symDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "symptom")
	public Set<Symptomdisease> getSymptomdiseases() {
		return this.symptomdiseases;
	}

	public void setSymptomdiseases(Set<Symptomdisease> symptomdiseases) {
		this.symptomdiseases = symptomdiseases;
	}

}
