package com.sbnz.doctor.model;
// Generated Aug 26, 2018 4:00:55 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Therapy generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "therapy", catalog = "sbnz")
public class Therapy implements java.io.Serializable {

	private Long therapyId;
	private Disease disease;
	private Medicine medicine;
	private Patient patient;
	private User user;
	private Date therapyDate;

	public Therapy() {
	}

	public Therapy(Disease disease, Medicine medicine, Patient patient, User user, Date therapyDate) {
		this.disease = disease;
		this.medicine = medicine;
		this.patient = patient;
		this.user = user;
		this.therapyDate = therapyDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "THERAPY_ID", unique = true, nullable = false)
	public Long getTherapyId() {
		return this.therapyId;
	}

	public void setTherapyId(Long therapyId) {
		this.therapyId = therapyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DISEASE_ID", nullable = false)
	public Disease getDisease() {
		return this.disease;
	}

	public void setDisease(Disease disease) {
		this.disease = disease;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEDICINE_ID", nullable = false)
	public Medicine getMedicine() {
		return this.medicine;
	}

	public void setMedicine(Medicine medicine) {
		this.medicine = medicine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PATIENT_ID", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "THERAPY_DATE", nullable = false, length = 19)
	public Date getTherapyDate() {
		return this.therapyDate;
	}

	public void setTherapyDate(Date therapyDate) {
		this.therapyDate = therapyDate;
	}

}
