/* KORISNICI */
INSERT INTO USER VALUES(1, 'Shawn', 'McKinney', 'admin', 'A', '123');
INSERT INTO USER VALUES(2, 'Michael', 'White', 'doctor', 'D', '123');
INSERT INTO USER VALUES(3, 'Alma', 'Grimsley', 'doctor2', 'D', '123');
INSERT INTO USER VALUES(4, 'Rose', 'Patrick', 'doctor3', 'D', '123');
INSERT INTO USER VALUES(5, 'Anthony', 'Harrell', 'doctor4', 'D', '123');

/* PACIJENTI */
/* Pacijent za monitoring, alergican na dva sastojka */
INSERT INTO PATIENT VALUES(1, 'John', 'Roessler');
/* Alergican na dva leka */
INSERT INTO PATIENT VALUES(2, 'Johnnie', 'Critchlow');
/* Possible chronic diseases */
INSERT INTO PATIENT VALUES(3, 'Kelly', 'Summerlin');
/* Possible addict */
INSERT INTO PATIENT VALUES(4, 'Maria', 'Spears');
/* Weak immunity */
INSERT INTO PATIENT VALUES(5, 'Stephen', 'George');
/* Sinusna infekcija - zadovoljen specificni zahtev */
INSERT INTO PATIENT VALUES(6, 'Viola', 'Via');
/* Chronic kidney disease */
INSERT INTO PATIENT VALUES(7, 'Jacklyn', 'Emerson');
/* Acute kidney failure */
INSERT INTO PATIENT VALUES(8, 'Norman', 'Durham');

/* BOLESTI */
INSERT INTO DISEASE VALUES(1, 'Cold', 'PREHL');
INSERT INTO DISEASE VALUES(2, 'Fever', 'GROZN');
INSERT INTO DISEASE VALUES(3, 'Tonsillitis', 'UPAKR');
INSERT INTO DISEASE VALUES(4, 'Sinus infection', 'SININ');
INSERT INTO DISEASE VALUES(5, 'Hypertension', 'HIPTE');
INSERT INTO DISEASE VALUES(6, 'Diabetes', 'DIJBE');
INSERT INTO DISEASE VALUES(7, 'Chronic kidney disease', 'HRBUB');
INSERT INTO DISEASE VALUES(8, 'Acute kidney failure', 'AKBUB');

/* SIMPTOMI */
INSERT INTO SYMPTOM VALUES(1, 'Nose leaking', 'CURNO', 0);
INSERT INTO SYMPTOM VALUES(2, 'Headache', 'GLAVB', 0);
INSERT INTO SYMPTOM VALUES(3, 'Sneezing', 'KIJAN', 0);
INSERT INTO SYMPTOM VALUES(4, 'Cough', 'KASHA', 0);
INSERT INTO SYMPTOM VALUES(5, 'Sore throat', 'BOLUG', 0);
INSERT INTO SYMPTOM VALUES(6, 'Temperature greater than 38°C', 'TEM38', 0);
INSERT INTO SYMPTOM VALUES(7, 'Shivering', 'DRHTI', 0);
INSERT INTO SYMPTOM VALUES(8, 'Pain spreading to the ears', 'BOLOU', 0);
INSERT INTO SYMPTOM VALUES(9, 'Temperature in between 40°C and 41°C', 'T4041', 0);
INSERT INTO SYMPTOM VALUES(10, 'Loss of appetite', 'GUBAP', 0);
INSERT INTO SYMPTOM VALUES(11, 'Tiredness', 'TIRED', 0);
INSERT INTO SYMPTOM VALUES(12, 'Yellow nasal secretion', 'ZHNOS', 0);
INSERT INTO SYMPTOM VALUES(13, 'Swelling around the eyes', 'OOCHI', 0);
INSERT INTO SYMPTOM VALUES(14, 'Frequent urination', 'CESTO', 0);
INSERT INTO SYMPTOM VALUES(15, 'Loss of body weight', 'GUBTT', 0);
INSERT INTO SYMPTOM VALUES(16, 'Fatigue', 'ZAMOR', 0);
INSERT INTO SYMPTOM VALUES(17, 'Nausea and vomiting', 'MUPOV', 0);
INSERT INTO SYMPTOM VALUES(18, 'Nocturia', 'NOCTA', 0);
INSERT INTO SYMPTOM VALUES(19, 'Swelling around legs and joints', 'ONOZG', 0);
INSERT INTO SYMPTOM VALUES(20, 'Strangulation', 'GUSHI', 0);
INSERT INTO SYMPTOM VALUES(21, 'Chest pain', 'BOLGR', 0);
INSERT INTO SYMPTOM VALUES(22, 'Diarrhea', 'PROLJ', 0);
INSERT INTO SYMPTOM VALUES(23, 'In last 6 months high blood pressure has been registered at least 10 times', 'VISPR', 1);
INSERT INTO SYMPTOM VALUES(24, 'In last 60 days patient had cold or fever', 'PRG60', 1);
INSERT INTO SYMPTOM VALUES(25, 'Patient is recovering from operation', 'OPORO', 0);
INSERT INTO SYMPTOM VALUES(26, 'Received antibiotics in last 21 days', 'ANB21', 1);
INSERT INTO SYMPTOM VALUES(27, 'Disease with high body temperature has been observed in the last 14 days', 'TEM14', 1);
INSERT INTO SYMPTOM VALUES(28, 'Patient is suffering from hipertension more than 6 months', 'HIPT6', 1);
INSERT INTO SYMPTOM VALUES(29, 'Patient is suffering from diabetes', 'DIANW', 1);

/* SIMPTOMI-BOLESTI */
INSERT INTO SYMPTOMDISEASE VALUES(1, 1, 1, 0);
INSERT INTO SYMPTOMDISEASE VALUES(2, 2, 1, 0);
INSERT INTO SYMPTOMDISEASE VALUES(3, 3, 1, 0);
INSERT INTO SYMPTOMDISEASE VALUES(4, 4, 1, 0);
INSERT INTO SYMPTOMDISEASE VALUES(5, 5, 1, 0);
INSERT INTO SYMPTOMDISEASE VALUES(6, 1, 2, 0);
INSERT INTO SYMPTOMDISEASE VALUES(7, 2, 2, 0);
INSERT INTO SYMPTOMDISEASE VALUES(8, 3, 2, 0);
INSERT INTO SYMPTOMDISEASE VALUES(9, 4, 2, 0);
INSERT INTO SYMPTOMDISEASE VALUES(10, 5, 2, 0);
INSERT INTO SYMPTOMDISEASE VALUES(11, 7, 2, 0);
INSERT INTO SYMPTOMDISEASE VALUES(12, 6, 2, 0);
INSERT INTO SYMPTOMDISEASE VALUES(13, 5, 3, 0);
INSERT INTO SYMPTOMDISEASE VALUES(14, 8, 3, 0);
INSERT INTO SYMPTOMDISEASE VALUES(15, 9, 3, 0);
INSERT INTO SYMPTOMDISEASE VALUES(16, 7, 3, 0);
INSERT INTO SYMPTOMDISEASE VALUES(17, 10, 3, 0);
INSERT INTO SYMPTOMDISEASE VALUES(18, 11, 3, 0);
INSERT INTO SYMPTOMDISEASE VALUES(19, 12, 3, 0);
INSERT INTO SYMPTOMDISEASE VALUES(20, 2, 3, 0);
INSERT INTO SYMPTOMDISEASE VALUES(21, 13, 4, 0);
INSERT INTO SYMPTOMDISEASE VALUES(22, 2, 4, 0);
INSERT INTO SYMPTOMDISEASE VALUES(23, 12, 4, 0);
INSERT INTO SYMPTOMDISEASE VALUES(24, 5, 4, 0);
INSERT INTO SYMPTOMDISEASE VALUES(25, 6, 4, 0);
INSERT INTO SYMPTOMDISEASE VALUES(26, 4, 4, 0);
INSERT INTO SYMPTOMDISEASE VALUES(27, 24, 4, 1);
INSERT INTO SYMPTOMDISEASE VALUES(28, 23, 5, 0);
INSERT INTO SYMPTOMDISEASE VALUES(29, 14, 6, 0);
INSERT INTO SYMPTOMDISEASE VALUES(30, 15, 6, 0);
INSERT INTO SYMPTOMDISEASE VALUES(31, 16, 6, 0);
INSERT INTO SYMPTOMDISEASE VALUES(32, 17, 6, 0);
INSERT INTO SYMPTOMDISEASE VALUES(33, 18, 7, 0);
INSERT INTO SYMPTOMDISEASE VALUES(34, 16, 7, 0);
INSERT INTO SYMPTOMDISEASE VALUES(35, 19, 7, 0);
INSERT INTO SYMPTOMDISEASE VALUES(36, 20, 7, 0);
INSERT INTO SYMPTOMDISEASE VALUES(37, 21, 7, 0);
INSERT INTO SYMPTOMDISEASE VALUES(38, 28, 7, 1);
INSERT INTO SYMPTOMDISEASE VALUES(39, 29, 7, 1);
INSERT INTO SYMPTOMDISEASE VALUES(40, 16, 8, 0);
INSERT INTO SYMPTOMDISEASE VALUES(41, 20, 8, 0);
INSERT INTO SYMPTOMDISEASE VALUES(42, 19, 8, 0);
INSERT INTO SYMPTOMDISEASE VALUES(43, 22, 8, 0);
INSERT INTO SYMPTOMDISEASE VALUES(44, 25, 8, 1);
INSERT INTO SYMPTOMDISEASE VALUES(45, 26, 8, 1);
INSERT INTO SYMPTOMDISEASE VALUES(46, 27, 8, 1);

/* DIJAGNOZE */
INSERT INTO DIAGNOSIS VALUES(1, 2, 6, 1, '2018-08-09', 1);
INSERT INTO DIAGNOSIS VALUES(2, 2, 7, 6, '2018-01-09', 1);
INSERT INTO DIAGNOSIS VALUES(3, 2, 8, 2, '2018-09-01', 1);

INSERT INTO DIAGNOSIS VALUES(4, 2, 3, 5, '2018-01-09', 1);
INSERT INTO DIAGNOSIS VALUES(5, 2, 3, 5, '2018-01-09', 1);
INSERT INTO DIAGNOSIS VALUES(6, 2, 3, 5, '2018-01-09', 1);
INSERT INTO DIAGNOSIS VALUES(7, 2, 3, 5, '2018-01-09', 1);
INSERT INTO DIAGNOSIS VALUES(8, 2, 3, 5, '2018-01-09', 1);
INSERT INTO DIAGNOSIS VALUES(9, 2, 3, 5, '2018-01-09', 1);
INSERT INTO DIAGNOSIS VALUES(10, 2, 2, 5, '2018-01-09', 1);
INSERT INTO DIAGNOSIS VALUES(11, 2, 2, 5, '2018-01-09', 1);
INSERT INTO DIAGNOSIS VALUES(12, 2, 2, 5, '2018-01-09', 1);
INSERT INTO DIAGNOSIS VALUES(13, 2, 2, 5, '2018-01-09', 1);

/* SASTOJCI */
INSERT INTO INGREDIENT VALUES(1, 'Abietis oil');
INSERT INTO INGREDIENT VALUES(2, 'Aripiprazole');
INSERT INTO INGREDIENT VALUES(3, 'Factor X');
INSERT INTO INGREDIENT VALUES(4, 'Fosfomycin trometamol');
INSERT INTO INGREDIENT VALUES(5, 'Abietis oil');

/* LEKOVI */
INSERT INTO MEDICINE VALUES(1, 'Paracetamol', 'P');
INSERT INTO MEDICINE VALUES(2, 'Ibuprofen', 'P');
INSERT INTO MEDICINE VALUES(3, 'Codeine', 'P');
INSERT INTO MEDICINE VALUES(4, 'Oritavancin', 'A');
INSERT INTO MEDICINE VALUES(5, 'Linezolid', 'A');
INSERT INTO MEDICINE VALUES(6, 'Tigecycline', 'A');
INSERT INTO MEDICINE VALUES(7, 'Zocor', 'O');
INSERT INTO MEDICINE VALUES(8, 'Clonazepam', 'O');
INSERT INTO MEDICINE VALUES(9, 'Lidex', 'O');

/* TERAPIJE */
INSERT INTO THERAPY VALUES(1, 1, 4, 2, 3, '2018-08-18');
INSERT INTO THERAPY VALUES(2, 2, 4, 3, 3, '2018-08-18');
INSERT INTO THERAPY VALUES(3, 3, 4, 4, 4, '2018-08-18');
INSERT INTO THERAPY VALUES(4, 1, 4, 5, 3, '2018-08-18');
INSERT INTO THERAPY VALUES(5, 2, 4, 2, 4, '2018-08-18');
INSERT INTO THERAPY VALUES(6, 3, 4, 3, 3, '2018-08-18');
INSERT INTO THERAPY VALUES(7, 4, 5, 4, 4, '2018-08-18');
INSERT INTO THERAPY VALUES(8, 5, 5, 4, 3, '2018-08-18');
INSERT INTO THERAPY VALUES(9, 6, 5, 4, 4, '2018-08-18');
INSERT INTO THERAPY VALUES(10, 4, 5, 4, 3, '2018-08-18');
INSERT INTO THERAPY VALUES(11, 5, 5, 4, 4, '2018-08-18');
INSERT INTO THERAPY VALUES(12, 6, 5, 4, 3, '2018-08-18');
INSERT INTO THERAPY VALUES(13, 4, 5, 4, 4, '2018-08-18');
INSERT INTO THERAPY VALUES(14, 5, 5, 4, 3, '2018-08-18');
INSERT INTO THERAPY VALUES(15, 6, 5, 4, 4, '2018-08-18');
INSERT INTO THERAPY VALUES(16, 4, 5, 4, 3, '2018-08-18');
INSERT INTO THERAPY VALUES(17, 5, 5, 4, 4, '2018-08-18');
INSERT INTO THERAPY VALUES(18, 6, 5, 4, 3, '2018-08-18');

/* LEKOVI - SASTOJCI */
INSERT INTO INGREDIENTMEDICINE VALUES(1, 4, 2);
INSERT INTO INGREDIENTMEDICINE VALUES(2, 4, 3);
INSERT INTO INGREDIENTMEDICINE VALUES(3, 5, 5);
INSERT INTO INGREDIENTMEDICINE VALUES(4, 6, 1);
INSERT INTO INGREDIENTMEDICINE VALUES(5, 7, 4);

/* LEKOVI - ALERGIJE */
INSERT INTO ALLERGY VALUES(1, 1, 2);
INSERT INTO ALLERGY VALUES(2, 1, 3);

/* SASTOJCI - ALERGIJE */
INSERT INTO MEDICINEALLERGY VALUES(1, 2, 1);
INSERT INTO MEDICINEALLERGY VALUES(2, 2, 8);